"""slop CLI — ``lint`` / ``check`` / ``rules`` / ``doctor`` / ``init``.

Scans a root into a Corpus, runs the rule dispatcher, renders findings (human or
JSON), and returns an exit code: 0 clean / 1 violations (any ERROR finding) /
2 error.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from .config import AnalysisConfig
from .dispatch import Dispatcher, Report
from .finding import Severity
from .scope import scan_corpus
from .rules import RULE_REGISTRY


def lint(root: str | Path, output: str = "human", *, rules=RULE_REGISTRY) -> int:
    root = Path(root)
    config = AnalysisConfig.load(root, rules)
    corpus = scan_corpus(root, config)
    report = Dispatcher(rules, config).run(corpus)
    if output == "json":
        print(json.dumps(report.as_dict(), indent=2))
    else:
        print(_human(report))
    return report.exit_code()


def check(target: str, root: str | Path, output: str = "human") -> int:
    """Lint with only the rules matching ``target`` — an exact rule name
    (``complexity.cyclomatic``) or a namespace family (``complexity``)."""
    selected = [r for r in RULE_REGISTRY
                if r.name == target or r.name.startswith(target + ".")]
    if not selected:
        print(f"slop: no rule or family matches '{target}'. Try `slop rules`.", file=sys.stderr)
        return 2
    return lint(root, output, rules=selected)


def rules_cmd(output: str = "human") -> int:
    """List the rule registry: name, altitudes, disposition."""
    rows = []
    for r in sorted(RULE_REGISTRY, key=lambda x: x.name):
        rc = r.default_config()
        alts = ",".join(sorted(k.value for k in r.altitudes))
        # A rule whose default severity is INFO emits observations; otherwise verdicts.
        dispo = "observation" if rc.severity is Severity.INFO else f"verdict/{rc.severity.label()}"
        rows.append((r.name, alts, dispo))
    if output == "json":
        print(json.dumps([{"name": n, "altitudes": a, "disposition": d} for n, a, d in rows], indent=2))
        return 0
    width = max((len(n) for n, _, _ in rows), default=4)
    print(f"{len(rows)} rules\n")
    for n, a, d in rows:
        print(f"  {n:<{width}}  {d:<18}  [{a}]")
    return 0


def doctor() -> int:
    """Report the tools slop relies on. Missing optional tools degrade gracefully."""
    print("slop doctor\n")
    ok = True
    try:
        import tree_sitter  # noqa: F401
        print("  [ok]   tree-sitter (parsing)")
    except Exception as exc:  # noqa: BLE001
        print(f"  [FAIL] tree-sitter not importable: {exc}")
        ok = False
    if shutil.which("git"):
        print("  [ok]   git (hotspots churn signal)")
    else:
        print("  [warn] git not found — the hotspots rule will be silent")
    print("\nready" if ok else "\nmissing required tooling")
    return 0 if ok else 2


def init(root: str | Path) -> int:
    """Emit a ``.slop.toml`` template from each rule's default config."""
    path = Path(root) / ".slop.toml"
    if path.exists():
        print(f"slop: {path} already exists; not overwriting", file=sys.stderr)
        return 2
    path.write_text(_template())
    print(f"wrote {path}")
    return 0


def _template() -> str:
    lines = ["# slop configuration — generated by `slop init`.",
             "# Uncomment and edit to override a rule's defaults.\n"]
    for r in sorted(RULE_REGISTRY, key=lambda x: x.name):
        rc = r.default_config()
        lines.append(f'# [rules."{r.name}"]')
        lines.append(f"# enabled = {str(rc.enabled).lower()}")
        if rc.severity is not Severity.INFO:
            lines.append(f'# severity = "{rc.severity.label()}"')
        for k, v in rc.thresholds.items():
            lines.append(f"# thresholds.{k} = {json.dumps(v)}")
        for k, v in rc.params.items():
            lines.append(f"# params.{k} = {json.dumps(v)}")
        lines.append("")
    return "\n".join(lines)


def _human(report: Report) -> str:
    lines: list[str] = []
    verdicts = report.verdicts()
    observations = report.observations()

    if verdicts:
        lines.append("VERDICTS")
        for v in sorted(verdicts, key=lambda f: (-int(f.severity), f.rule)):
            lines.append(f"  [{v.severity.label()}] {v.rule}  ·  {v.component.qualname}")
            lines.append(f"      {v.message}")
            lines.append(f"      → {v.action.value}: {v.prescription}")
        lines.append("")

    if observations:
        lines.append("OBSERVATIONS")
        for o in observations:
            lines.append(f"  [info] {o.rule}  ·  {o.component.qualname}")
            lines.append(f"      {o.message}")
        lines.append("")

    if report.zero_visited:
        lines.append(f"note: {len(report.zero_visited)} enabled rule(s) examined 0 components: "
                     f"{', '.join(report.zero_visited)}")
        lines.append("")

    s = report.as_dict()["summary"]
    summary = (f"{s['verdicts']} verdict(s) ({s['errors']} error, {s['warnings']} warning), "
               f"{s['observations']} observation(s) — exit {s['exit_code']}")
    if not report.findings:
        return "clean — no findings\n\n" + summary
    lines.append(summary)
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="slop", description="agentic code-quality linter")
    sub = parser.add_subparsers(dest="command", required=True)

    p_lint = sub.add_parser("lint", help="lint a source root")
    p_lint.add_argument("--root", default=".", help="source root to scan (default: cwd)")
    p_lint.add_argument("--output", choices=["human", "json"], default="human")

    p_check = sub.add_parser("check", help="lint with only one rule or namespace family")
    p_check.add_argument("target", help="a rule name (complexity.cyclomatic) or family (complexity)")
    p_check.add_argument("--root", default=".")
    p_check.add_argument("--output", choices=["human", "json"], default="human")

    p_rules = sub.add_parser("rules", help="list the rule registry")
    p_rules.add_argument("--output", choices=["human", "json"], default="human")

    sub.add_parser("doctor", help="check slop's tooling dependencies")

    p_init = sub.add_parser("init", help="write a .slop.toml config template")
    p_init.add_argument("--root", default=".")

    args = parser.parse_args(argv)
    try:
        if args.command == "lint":
            return lint(args.root, args.output)
        if args.command == "check":
            return check(args.target, args.root, args.output)
        if args.command == "rules":
            return rules_cmd(args.output)
        if args.command == "doctor":
            return doctor()
        if args.command == "init":
            return init(args.root)
    except Exception as exc:  # noqa: BLE001 — top-level boundary: any failure is exit 2
        print(f"slop: error: {exc}", file=sys.stderr)
        return 2
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
